config:
  checksum: false
  install_tree:
    root: /cvmfs/sw-nightlies.hsf.org/spackages6
    projections:
      all: "{name}/{version}/{architecture.target}-{architecture.os}-{compiler.name}{compiler.version}-opt/{hash:5}"
      build_type=Debug: "{name}/{version}/{architecture.target}-{architecture.os}-{compiler.name}{compiler.version}-dbg/{hash:5}"
