config:
  # fixes installation errors on afs
  allow_sgid: false
  install_tree:
    projections:
      all: "{name}/{version}/{architecture.target}-{architecture.os}-{compiler.name}{compiler.version}-opt/{hash:5}"
      build_type=Debug: "{name}/{version}/{architecture.target}-{architecture.os}-{compiler.name}{compiler.version}-dbg/{hash:5}"
