packages:
  all:
    target: [broadwell]
    variants: build_type=Release
    providers:
      gl: [mesa18]
      glu: [mesa18]
  mesa18:
    variants: ~llvm+glx+opengl swr=none
  range-v3:
    # avoid building doxygen
    variants: ~doc
  geant4:
    variants: ~qt~opengl+vecgeom
  marlin:
    # avoid building mariadb
    variants: ~lccd
  mesa:
    # avoid building llvm
    variants: ~llvm+glx+opengl swr=none
  boost:
    variants: +python
  dd4hep:
    variants: +geant4+lcio+hepmc3
  xercesc:
    variants: cxxstd=11
  root:
    version: [6.22.06]
    variants: +davix+gsl+asimage+math~memstat+minuit+mlp~mysql+opengl~postgres~pythia6+pythia8+python~qt4+r+root7+rootfit+rpath~shadow+sqlite+ssl~table+tbb+threads+tmva+unuran+vc+vdt+vmc+x+xml+xrootd cxxstd=17
  # avoid issue https://github.com/spack/spack/issues/16803
  # and use variant that allows to install older versions of whizard
  ocaml:
    version: [4.10.0]
    variants: ~force-safe-string
  # Avoid concretizer conflict for edm4hep
  pythia8:
    version: [8303]
  gaudi:
    version: [35.0]
  # gaudi v34 does not work with python 3.8
  # setting the version explicitly avoids concretizer errors
  python:
    version: [3.7.8]
  delphes:
    # includes some fixes to the trackcovariance module that are
    # needed in fccsw
    version: [3.4.3pre06]
  # for compatibility with tensorflow
  py-numpy:
    version: [1.18.5]
  py-tensorflow:
    variants: [~cuda~nccl]
  # build error on centos7 with version 7.1.0
  fmt:
    version: [6.1.2]
  curl:
    version: [7.72.0]
  expat:
    version: [2.2.9]
  perl:
    version: [5.30.3]
  whizard:
    variants: ~fastjet~latex+lcio~lhapdf+openloops~openmp+pythia8 hepmc=2
  cmake:
    version: [3.18.4]


